### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by ComputerScientist-01** [fireship-io/javascript-millionaire#3]
await welcome();
^^^^^

SyntaxError: Unexpected reserved word

**Comment by tobyab** [comment]
Make sure you're using node 14 or above.

**Comment by ComputerScientist-01** [comment]
after upgrading node version to 17
![Screenshot from 2022-01-29 11-10-47](https://user-images.githubusercontent.com/39644109/151649075-0bf3e497-a9ad-4739-b2bd-b2c1dfe6dbd4.png)

**Comment by tobyab** [comment]
First, run `npx firequiz`. NPM will then prompt you to install some packages. Just click `y` on your keyboard, and then it should work.

**Comment by ComputerScientist-01** [comment]
it works now thanks
